-- AlterTable
ALTER TABLE "Prueba" ALTER COLUMN "printMetodo" DROP DEFAULT,
ALTER COLUMN "printMetodo" SET DATA TYPE TEXT,
ALTER COLUMN "printBold" DROP DEFAULT,
ALTER COLUMN "printBold" SET DATA TYPE TEXT,
ALTER COLUMN "printNotas" DROP DEFAULT,
ALTER COLUMN "printNotas" SET DATA TYPE TEXT;
